### ISSUE TITLE
Split benchmark.csv file into various files accoring to project dataset

### ISSUE THREAD

**Issue by manand881** [OpenDroneMap/odm-benchmarks#12]
The benchmark.csv file contains the bench marking results of all datasets in a single file. when one has to benchmark, one compares how the results vary for a single dataset at a given time. I suggest that the bench marking data be split into different files according to the data set that is being processed so we can write make a static website hosted on github pages in this repository which visualizes the benchmark data

**Comment by coreysnipes** [comment]
@manand881 This is a good suggestion.  I started with a single file to keep things simple, but I agree it would be more flexible and easier to manage with separate files.  I'll admit I am not very familiar with github pages capabilities.  Do you think you could help put something together for visualization?

**Comment by manand881** [comment]
Yes it would be a pleasure, but I'm not as good as the rest of the developers here, I don't know if they're going to like my work.

**Comment by coreysnipes** [comment]
@manand881 No need to worry about that.  All contributions are appreciated, and even the most experienced developers have things they don't know.  (Usually, lots of things.)  Any help you can provide with github pages will be great.

**Comment by manand881** [comment]
OK, ill do my best. I have an exam on Friday, so ill do it on Saturday and give you a pull request which you can merge.

**Comment by coreysnipes** [comment]
I added a simple nodejs parser for the benchmarks data, so you can now view results by dataset, or by version.  See the top of the README at https://github.com/OpenDroneMap/odm-benchmarks  This is all still in a single file and there's no data visualization, but it does make benchmarks data easier to browse IMO.

**Comment by coreysnipes** [comment]
I am closing this issue as the stated need is addressed by the data parser, but please feel free to open a new issue for the data visualization piece.
